clone:
  depth: 2
  recursive: true
  submodule_override:
    external/anyode: git://github.com/bjodah/anyode.git

build:
  image: bjodah/bjodahimg20dev:v1.0.2
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-10/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
    - CPLUS_INCLUDE_PATH=/opt/boost_1_72_p/include
  commands:
    - strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5  # stackoverflow.com/questions/54582864/
    - ./scripts/ci.sh pyodeint
    - ./scripts/prepare_deploy.sh
    - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodeint
    source: deploy/
    target: ~
    recursive: true
    delete: false
