build:
  image: bjodah/bjodahimg16dev:v1.3
  environment:
    - CPLUS_INCLUDE_PATH=/opt/boost_1_65_0/include
  commands:
    - echo "#error" >/opt/boost_1_65_0/include/boost/numeric/odeint/stepper/rosenbrock4_controller.hpp
    - ./scripts/ci.sh pyodeint
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodeint
    source: deploy/
    target: ~
    recursive: true
    delete: false
