build:
  image: bjodah/bjodahimg18dev:v1.2
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
  commands:
    - ./scripts/ci.sh pyodeint
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodeint
    source: deploy/
    target: ~
    recursive: true
    delete: false
