clone:
  default:
    image: plugins/git
    recursive: true
    submodule_override:
      external/anyode: git://github.com/bjodah/anyode.git

pipeline:

  build:
    image: bjodah/bjodahimg20:21.8
    environment:
      - CC=gcc-11
      - CXX=g++-11
      - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-11/bin/llvm-symbolizer
      - ASAN_OPTIONS=symbolize=1
      - CPLUS_INCLUDE_PATH=/opt/boost-1.77.0/include
    commands:
      - ./scripts/ci.sh pyodeint
      - ./scripts/prepare_deploy.sh
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
      - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

  deploy-artifacts:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "sayyy.mooo.com" ]
    port: 40022
    user: pyodeint
    secrets: [ rsync_key ]  # secret only set fro event "push" not "pull_request"
    source: ./deploy/public_html/branches/.
    target: ~/public_html/branches/
