build:
  image: bjodah/bjodahimg16dev:latest
  commands:
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - export CPLUS_INCLUDE_PATH=/opt/boost_1_63_0
    - echo "#error" >/opt/boost_1_63_0/boost/numeric/odeint/stepper/rosenbrock4_controller.hpp
    - ./scripts/ci.sh pyodeint
    - (cd examples/; ipython2 nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
    - (cd examples/; ../scripts/render_index.sh *.html)
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyodeint
    source: deploy/
    target: ~
    recursive: true
    delete: false
