when:
  - event: [push]

# clone:
#   depth: 2
#   recursive: true
#   submodule_override:
#     external/anyode: git://github.com/bjodah/anyode.git

steps:
  - name: build-and-test
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:24
    environment:
      - PYTHONMALLOC=malloc
    commands:
      - ./scripts/ci.sh ${CI_REPO_NAME}
      - ./scripts/prepare_deploy.sh
      - if grep "DO-NOT-MERGE!" -R . --exclude ".woodpecker.yaml"; then exit 1; fi

# deploy:

#   rsync:
#     host: hera.physchem.kth.se
#     port: 22
#     user: pyodeint
#     source: deploy/
#     target: ~
#     recursive: true
#     delete: false
