{% set name = "pyodeint" %}
{% set version = "0.9.0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - boost
    - cython
  run:
    - python
    - numpy

test:
  imports:
    - pyodeint
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs pyodeint

about:
  home: https://github.com/bjodah/pyodeint
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python wrapper around odeint (from the boost C++ library)'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
