{% set name = "pyodeint" %}
{% set version = "0.10.0.dev0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  skip: True  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - pip
    - numpy 1.11.*
    - boost
    - cython
  run:
    - python
    - numpy >=1.11

test:
  imports:
    - pyodeint
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs pyodeint

about:
  home: https://github.com/bjodah/pyodeint
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python wrapper around odeint (from the boost C++ library)'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
